<?php 
/**
 * Avail - Point of Sale
 *
 * @category  Avail
 * @package   Avail_Pointofsale
 * @copyright 2012 Avail
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $helper = $this->helper('pointofsale'); ?>
<?php $pageViewedKey = $helper->getPageViewedKey() ?>
<?php $maxPageViewed = $helper->getMaxPageViewed() ?>

<!-- Begin Avail -->
<?php if ($this->isConfigured()) : ?>
    <?php if ($this->isDebugMode()) : ?>
    <div id="__avail_log__"></div>
    <?php endif; ?>
    
    <script type="text/javascript">
    //<![CDATA[
        function availCartItem(productId) {
            Cookie.setData('<?php echo $helper->getBuyButtonUrlParam() ?>_inc', 0);
            Cookie.setData('<?php echo $helper->getBuyButtonUrlParam() ?>', productId);
            setLocation(<?php echo "'" . $helper->getAddToCartUrl() . "product/'" ?>+productId);
        }
        
        function incrementAndDelete(incr, flush, limit) {
            var page_viewed = Cookie.getData(incr);
            if (page_viewed != null) {
                Cookie.setData(incr, page_viewed + 1);
            }
            if (page_viewed > limit) {
                Cookie.removeData(incr);
                Cookie.removeData(flush);
            }
        }
        
        Cookie.init({
            name: '<?php echo $helper->getInitCookieName() ?>',
            path: '/',
            domain: '<?php echo Mage::getModel('core/cookie')->getDomain() ?>' 
        }); 
    
    <?php if ($this->isDebugMode()) : ?>
        var emark = new Emark(true);
    <?php else: ?>
        var emark = new Emark();
    <?php endif; ?>

        incrementAndDelete('<?php echo $pageViewedKey ?>', '<?php echo $helper->getSearchPhraseKey() ?>', <?php echo $maxPageViewed ?>);
        incrementAndDelete('<?php echo $helper->getBuyButtonUrlParam() ?>_inc', '<?php echo $helper->getBuyButtonUrlParam() ?>', <?php echo $maxPageViewed ?>);
    
        <?php echo $helper->getJsCode(); ?>
        
        emark.commit();
    //]]>
    </script>
<?php endif; ?>
<!-- End Avail -->
